[package]
name = "chessarena"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.2.0"
ggez = "0.9.0"
rand = "0.8.5"
